const ACTION_TYPES = {
  TOGGLE_JOBS_LOADING: 'TOGGLE_JOBS_LOADING',
  RECEIVE_JOBS: 'RECEIVE_JOBS',
  RESET_JOBS: 'RESET_JOBS',
  REFRESH_JOBS: 'REFRESH_JOBS',
  RECEIVE_USER: 'RECEIVE_USER',
  CLEAN_USER: 'CLEAN_USER',
};

export default ACTION_TYPES;
